name: shared
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  core: 
    path: ../core

  # State management
  provider: ^4.3.2+2
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  cube:
    path: ../../packages/cube

  # UI
  auto_size_text: ^2.1.0
  flutter_svg: ^0.19.1

  # DBs
  shared_preferences: ^0.5.12+4
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

flutter:
  uses-material-design: true

  assets:
    - i18n/

